FSHOnly: true
#name: FSH-LOESUNGEN
canonical: http://gefyra.de/fhir/spezifizierer-workshop # Namensraum f체r FHIR-Artefakte (SUSHI h채ngt automatisch .../<Ressourcentyp>/<name> an)
#status: draft # draft | active | retired | unknown
version: 0.1.0 # gew체nschte Version f체r FHIR-Artefakte
fhirVersion: 4.0.1 # siehe http://hl7.org/fhir/directory.html
#depencencies:
#  ufp.core 0.5.1